### ISSUE TITLE
No icon on Ubuntu

### ISSUE THREAD

**Issue by superbonaci** [flathub/io.github.prateekmedia.appimagepool#5]
Installed the app like this:
```
$ flatpak install flathub io.github.prateekmedia.appimagepool
Looking for matches…
Required runtime for io.github.prateekmedia.appimagepool/x86_64/stable (runtime/org.gnome.Platform/x86_64/41) found in remote flathub
Do you want to install it? [Y/n]: Y

io.github.prateekmedia.appimagepool permissions:
    ipc      network      fallback-x11      pulseaudio      wayland      x11      dri      file access [1]     dbus access [2]

    [1] ~/Applications:create
    [2] org.freedesktop.Flatpak, org.freedesktop.Notifications


        ID                                                    Branch            Op            Remote             Download
 1. [✓] org.freedesktop.Platform.GL.default                   21.08             i             flathub            130,9 MB / 131,2 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-470-86             1.4               i             flathub            223,6 MB / 224,0 MB
 3. [✓] org.freedesktop.Platform.openh264                     2.0               i             flathub              1,5 MB / 1,5 MB
 4. [✓] org.gnome.Platform.Locale                             41                i             flathub              4,3 MB / 335,7 MB
 5. [✓] org.gtk.Gtk3theme.Greybird                            3.22              i             flathub             49,3 kB / 91,8 kB
 6. [✓] org.gnome.Platform                                    41                i             flathub            240,3 MB / 288,4 MB
 7. [✓] io.github.prateekmedia.appimagepool                   stable            i             flathub              9,8 MB / 9,9 MB

Installation complete.
```
When I write `AppImage Pool` on KDE/Plasma start menu, it has a blank icon. Could this be fixed?

**Comment by prateekmedia** [comment]
Restart your PC, else see if other flatpak app does the same.

**Comment by superbonaci** [comment]
Icon is displayed on Manjaro.

**Comment by superbonaci** [comment]
After rebooting on Ubuntu icon is displayed, minor errors though:
```
$ flatpak run io.github.prateekmedia.appimagepool
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/user/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/user/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/user/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/user/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _AdwHeaderBarState.initState.<anonymous closure> (package:libadwaita/src/widgets/adw/header_bar.dart:230)
<asynchronous suspension>

flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1196)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1017)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:535)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:948)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:137)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by prateekmedia** [comment]
Closing as these errors are common.
